# Generated by Django 3.2.8 on 2022-10-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='admin status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_develloper',
            field=models.BooleanField(default=False, verbose_name='develloper status'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_project_holder',
            field=models.BooleanField(default=False, verbose_name='project holder status'),
        ),
    ]
